### ISSUE TITLE
Organizar conteúdos com data em ordem decrescente

### ISSUE THREAD

**Issue by marcelabomfim** [marcelabomfim/CSSEHFODA#22]
Alguns conteúdos estão separados por ano (Artigos, Vídeos, Podcasts ..), isso é legal para que as pessoas busquem pelos mais atuais, por isso acho melhor deixar organizado de forma descrescente, do mais atual para o mais antigo.

**Comment by G4brym** [comment]
#23 
vê se tá bom assim, aproveitei e adicionei mais um artigo
